[colors]
[colors.primary]
background = "#121212"
foreground = "#ffffff"

[colors.normal]
black   = "#121212"
red     = "#db7b4d"
green   = "#98c7cd"
yellow  = "#e8a472"
blue    = "#879ecf"
magenta = "#cd989e"
cyan    = "#98b5cd"
white   = "#ffffff"

[colors.bright]
black   = "#9e9e9e"
red     = "#eeb295"
green   = "#a4d4da"
yellow  = "#f2b78c"
blue    = "#c7d2eb"
magenta = "#daa4aa"
cyan    = "#a4c2da"
white   = "#ffffff"

[colors.cursor]
text   = "#121212"
cursor = "#ffffff"
