accent = "#F6F7FB"
cursor = "#FF965C"
foreground = "#EDE7E0"
background = "#0B0D10"
selection_foreground = "#0B0D10"
selection_background = "#CFE8FF"

color0  = "#0B0D10"
color1  = "#FF6B4A"
color2  = "#e8a472"
color3  = "#FFD08A"
color4  = "#8FB1FF"
color5  = "#E7A5C8"
color6  = "#9DD4FF"
color7  = "#EDE7E0"

color8  = "#7A808A"
color9  = "#FFB089"
color10 = "#FFD08A"
color11 = "#FFE0B0"
color12 = "#C8D6FF"
color13 = "#F2B6D9"
color14 = "#BFE6FF"
color15 = "#F6F7FB"
