accent = "#ffffff"
cursor = "#db7b4d"
foreground = "#ffffff"
background = "#121212"
selection_foreground = "#121212"
selection_background = "#db7b4d"

color0 = "#121212"
color1 = "#db7b4d"
color2 = "#98c7cd"
color3 = "#e8a472"
color4 = "#879ecf"
color5 = "#cd989e"
color6 = "#98b5cd"
color7 = "#ffffff"
color8 = "#9e9e9e"
color9 = "#eeb295"
color10 = "#a4d4da"
color11 = "#f2b78c"
color12 = "#c7d2eb"
color13 = "#daa4aa"
color14 = "#a4c2da"
color15 = "#ffffff"
